// Generated by scripts/logo-assets.mjs — do not edit by hand. Run `npm run logo`.
//
// `wordmark` is where the logotype sits inside the artwork, as a fraction of
// the image width: it starts at the left edge of the "M" of Mila and ends at
// the right edge of the "m" of Ecosystem.

export const logoFull = {
  src: "/images/logo-full.webp",
  ratio: 3.5211,
  wordmark: { start: 0.2857, end: 0.9990 },
} as const;

export const logoLockup = {
  src: "/images/logo-lockup.webp",
  srcDark: "/images/logo-lockup-dark.webp",
  ratio: 3.5185,
  wordmark: { start: 0.2857, end: 0.9990 },
} as const;
